name: Build, Docs & Deploy

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Build
        run: |
          npm install
          npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: build
          path: ./dist

  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: 'import\(.*\)\.'
          replace: ' '
          include: './src/**'
          regex: true

      - name: Build
        run: |
          npm install
          npm run doc

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: docs
          path: ./docs

  deploy:
    name: Deploy to GitHub Pages
    needs: [build, docs]
    runs-on: ubuntu-latest

    outputs:
      page_url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Download build
        uses: actions/download-artifact@v3.0.2
        with:
          name: build
          path: .

      - name: Download docs
        uses: actions/download-artifact@v3.0.2
        with:
          name: docs
          path: ./docs

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v0
        with:
          path: .
          retention-days: 1

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          timeout: 1800000
